# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import myproject.myapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=myproject.myapp.models.get_upload_dir)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
