# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171105_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
    ]
