language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install coveralls

# command to run tests
#script: python pointillism/setup.py test
script: coverage run --source pointillism/pointillism pointillism/setup.py test

after_success:
    coveralls
