language: python
python:
  - "3.6" # note add 3.7 once it's available on Travis
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.1"
  - "2.7"

install:
  - pip install coveralls

before_script: 
  - cd pointillism
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

script: coverage run --source pointillism setup.py test

after_success:
    coveralls
