branch-defaults:
  tbs-new-aws-updates:
    environment: myproject
environment-defaults:
  myproject:
    branch: null
    repository: null
global:
  application_name: myproject
  default_ec2_keyname: myproject-mac-key
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.4 running
    on 64bit Amazon Linux/2.9.3
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
